#
# This file was generated by VS2CMake tool (internal-only)!
# You probably need to modify the generated files to meet your requirements.
#

cmake_minimum_required(VERSION 2.8)

SET(MY_TARGET_NAME GoogleTest)

SET(GoogleTest_SRC 
    "gtest-all.cc" 
    "gtest_main.cc" 
)
